"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import {
  AlertTriangle,
  Copy,
  ExternalLink,
  Loader2,
  RefreshCw,
  Search,
} from "lucide-react";
import { Logo } from "@/components/Logo";
import {
  clearSyncToken,
  fetchFamilyHistory,
  getSyncToken,
} from "@/lib/sync";
import type { HistoryEntry } from "@/lib/history";
import { formatRelativeTime } from "@/lib/history";

type Loaded =
  | { state: "idle" }
  | { state: "loading" }
  | { state: "ready"; entries: HistoryEntry[] }
  | { state: "error"; message: string; status?: number };

export default function AdminPage() {
  const [data, setData] = useState<Loaded>({ state: "idle" });
  const [query, setQuery] = useState("");
  const [signedIn, setSignedIn] = useState(false);

  const load = useCallback(async () => {
    if (!getSyncToken()) {
      setSignedIn(false);
      return;
    }
    setSignedIn(true);
    setData({ state: "loading" });
    const result = await fetchFamilyHistory();
    if (result.ok) {
      setData({ state: "ready", entries: result.entries });
    } else {
      if (result.status === 401) {
        clearSyncToken();
        setSignedIn(false);
        return;
      }
      setData({ state: "error", message: result.error, status: result.status });
    }
  }, []);

  useEffect(() => {
    load();
  }, [load]);

  const filtered = useMemo(() => {
    if (data.state !== "ready") return [];
    const q = query.trim().toLowerCase();
    if (!q) return data.entries;
    return data.entries.filter((e) => e.url.toLowerCase().includes(q));
  }, [data, query]);

  const deviceStats = useMemo(() => {
    if (data.state !== "ready") return [];
    const counts = new Map<string, number>();
    for (const e of data.entries) {
      const label = (e as HistoryEntry & { deviceLabel?: string }).deviceLabel ?? "unlabeled";
      counts.set(label, (counts.get(label) ?? 0) + 1);
    }
    return Array.from(counts.entries()).sort((a, b) => b[1] - a[1]);
  }, [data]);

  function handleExport() {
    if (data.state !== "ready") return;
    const json = JSON.stringify(
      {
        app: "qr-forever",
        version: 1,
        source: "family-admin",
        exportedAt: new Date().toISOString(),
        entries: data.entries,
      },
      null,
      2
    );
    const blob = new Blob([json], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `qr-forever-family-${new Date().toISOString().slice(0, 10)}.json`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }

  if (!signedIn) {
    return (
      <main className="flex-1 w-full grid place-items-center py-20 px-6">
        <div className="max-w-sm text-center space-y-4">
          <Logo size={44} />
          <h1 className="text-xl font-semibold">Sign in required</h1>
          <p className="text-sm text-[var(--color-ink-soft)]">
            The family history is token-protected. Head to sign-in and enter
            the family token to view it.
          </p>
          <Link
            href="/sign-in"
            className="inline-block px-4 py-2.5 rounded-xl bg-[var(--color-espresso)] text-[var(--color-paper)] text-sm font-medium hover:bg-[var(--color-espresso-hover)]"
          >
            Go to sign-in
          </Link>
        </div>
      </main>
    );
  }

  return (
    <main className="flex-1 w-full">
      <div className="mx-auto max-w-5xl px-6 py-10">
        <header className="flex items-start justify-between mb-8 gap-4">
          <Link href="/" className="flex items-center gap-3 hover:opacity-80">
            <Logo size={36} />
            <div>
              <div className="text-lg font-semibold tracking-tight">
                QR Forever · Family history
              </div>
              <div className="text-xs text-[var(--color-ink-muted)]">
                Every QR generated by anyone signed into the family space
              </div>
            </div>
          </Link>
          <div className="flex items-center gap-2">
            <button
              type="button"
              onClick={load}
              disabled={data.state === "loading"}
              className="inline-flex items-center gap-1.5 px-3 py-2 rounded-lg border border-[var(--color-line-strong)] hover:bg-[var(--color-surface-soft)] text-sm disabled:opacity-60"
            >
              <RefreshCw
                className={`size-4 ${data.state === "loading" ? "animate-spin" : ""}`}
              />
              Refresh
            </button>
            <button
              type="button"
              onClick={handleExport}
              disabled={data.state !== "ready" || data.entries.length === 0}
              className="px-3 py-2 rounded-lg border border-[var(--color-line-strong)] hover:bg-[var(--color-surface-soft)] text-sm disabled:opacity-40"
            >
              Export JSON
            </button>
          </div>
        </header>

        {data.state === "loading" && (
          <div className="py-20 grid place-items-center text-[var(--color-ink-muted)]">
            <Loader2 className="size-6 animate-spin" />
          </div>
        )}

        {data.state === "error" && (
          <div className="bg-red-50 border border-red-200 rounded-xl p-5 flex items-start gap-3 text-sm text-red-900">
            <AlertTriangle className="size-5 shrink-0 mt-0.5" />
            <div>
              <div className="font-medium">Couldn&apos;t load family history.</div>
              <div className="mt-1 text-red-800/80 break-all">
                {data.message}
              </div>
              <button
                type="button"
                onClick={load}
                className="mt-3 px-3 py-1.5 rounded border border-red-300 bg-[var(--color-surface)] hover:bg-red-50 text-xs"
              >
                Try again
              </button>
            </div>
          </div>
        )}

        {data.state === "ready" && (
          <>
            {deviceStats.length > 0 && (
              <div className="mb-6 grid grid-cols-2 md:grid-cols-4 gap-3">
                <StatCard
                  label="Total QRs"
                  value={data.entries.length.toString()}
                />
                <StatCard
                  label="Devices"
                  value={deviceStats.length.toString()}
                />
                <StatCard
                  label="Last synced"
                  value={
                    data.entries[0]
                      ? formatRelativeTime(data.entries[0].createdAt)
                      : "—"
                  }
                />
                <StatCard
                  label="Top device"
                  value={deviceStats[0]?.[0] ?? "—"}
                />
              </div>
            )}

            <div className="relative mb-4">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 size-4 text-[var(--color-ink-faint)]" />
              <input
                type="text"
                value={query}
                onChange={(e) => setQuery(e.target.value)}
                placeholder="Filter by URL…"
                className="w-full pl-10 pr-4 py-2.5 rounded-xl border border-[var(--color-line-strong)] text-sm focus:outline-none focus:ring-2 focus:ring-[var(--color-espresso)] focus:border-[var(--color-espresso)]"
              />
            </div>

            {filtered.length === 0 ? (
              <div className="py-16 text-center text-sm text-[var(--color-ink-muted)]">
                {data.entries.length === 0
                  ? "No QRs synced yet. Generate one from the home page while signed in."
                  : "No matches for that filter."}
              </div>
            ) : (
              <div className="bg-[var(--color-surface)] rounded-2xl border border-[var(--color-line)] shadow-sm overflow-hidden">
                <table className="w-full text-sm">
                  <thead className="bg-[var(--color-surface-soft)] text-xs uppercase tracking-wide text-[var(--color-ink-muted)]">
                    <tr>
                      <th className="text-left px-4 py-3">URL</th>
                      <th className="text-left px-4 py-3 w-40">When</th>
                      <th className="text-left px-4 py-3 w-40">Device</th>
                      <th className="px-4 py-3 w-8"></th>
                    </tr>
                  </thead>
                  <tbody>
                    {filtered.map((entry) => (
                      <AdminRow key={entry.id} entry={entry} />
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </>
        )}

        <footer className="mt-10 text-xs text-[var(--color-ink-muted)] flex gap-4">
          <Link href="/" className="hover:text-[var(--color-ink)]">
            ← Generator
          </Link>
          <Link href="/sign-in" className="hover:text-[var(--color-ink)]">
            Sign-in / sign-out
          </Link>
        </footer>
      </div>
    </main>
  );
}

function AdminRow({ entry }: { entry: HistoryEntry & { deviceLabel?: string } }) {
  const [copied, setCopied] = useState(false);
  function copy() {
    navigator.clipboard?.writeText(entry.url);
    setCopied(true);
    setTimeout(() => setCopied(false), 1200);
  }
  return (
    <tr className="border-t border-[var(--color-line)] hover:bg-[var(--color-surface-soft)]">
      <td className="px-4 py-3 break-all font-mono text-xs">
        <div className="flex items-center gap-2">
          <a
            href={entry.url}
            target="_blank"
            rel="noopener noreferrer"
            className="hover:text-[var(--color-ink)] inline-flex items-center gap-1"
          >
            {entry.url}
            <ExternalLink className="size-3 opacity-50" />
          </a>
        </div>
      </td>
      <td className="px-4 py-3 text-[var(--color-ink-soft)] whitespace-nowrap">
        <span title={new Date(entry.createdAt).toLocaleString()}>
          {formatRelativeTime(entry.createdAt)}
        </span>
      </td>
      <td className="px-4 py-3 text-[var(--color-ink-soft)] text-xs">
        {entry.deviceLabel ?? (
          <span className="text-[var(--color-ink-faint)]">unlabeled</span>
        )}
      </td>
      <td className="px-4 py-3 text-right">
        <button
          type="button"
          onClick={copy}
          className="p-1.5 rounded hover:bg-[var(--color-surface-soft)] text-[var(--color-ink-faint)] hover:text-[var(--color-ink-soft)]"
          title={copied ? "Copied!" : "Copy URL"}
          aria-label="Copy URL"
        >
          <Copy className="size-4" />
        </button>
      </td>
    </tr>
  );
}

function StatCard({ label, value }: { label: string; value: string }) {
  return (
    <div className="bg-[var(--color-surface)] rounded-xl border border-[var(--color-line)] p-3">
      <div className="text-xs text-[var(--color-ink-muted)] mb-0.5">{label}</div>
      <div className="text-lg font-semibold tracking-tight truncate">
        {value}
      </div>
    </div>
  );
}
